baseURL = "https://quebit.ai"
title = "Quebit"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Quebit" # title for frontpage, may include image
img = "img/pic01.jpg"
copyright = "quebit"
description = 'Where Traffic Meets Technology'
startbuttonText = "Get in Contact"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
images = ["img/pic01.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one ]
enable = true
style="1"
title = 'End-to-end traffic control solutions'
body = """Quebit is an advanced AI-powered traffic management system designed to adapt quickly to changing traffic patterns in real time.
It synchronises traffic signals within corridors to optimise traffic flow across city intersections. Our AI solution comes in a plug & play module that easily integrates with controllers supporting the UTMC protocol.
Through a user-friendly web platform, Quebit provides complete system visibility, control, and smart alerts for effective traffic management. Improve safety, reduce congestion, and enhance overall traffic efficiency with Quebit.
Invest in the future of traffic management. For more information, send us an contact us."""


[[params.one.icon]]
icon = "fa-car"
style = "1"

[[params.one.icon]]
icon = "fa-laptop"
style = "1"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "1"
label = "Dolor"

[[params.one.icon]]
icon = "fa-road"
style = "1"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "images/traffic_counts.jpg"
title = 'Monitor'
body = """
Through a web-based platform, Quebit offers full system visibility and control. Stay up-to-date with Quebit. Monitor real-time traffic patterns, get smart alerts and have the latest traffic insights. 
"""

[[params.two.section]]
img = "images/integrate.jpg"
title = 'Integrate'
body = """
Keep it simple. The Quebit module seamlessly integrates with all traffic controller hardware supporting the UTMC protocol.
Designed to work in perfect harmony with your existing traffic control system, allowing for smooth, safe and efficient communication between the two. 
"""

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Simulate'
body = """
Our advanced traffic simulation software uses real-world data to accurately model traffic behaviour, giving you an accurate representation of traffic patterns, and enabling data-driven decisions. Gain valuable insights and experience the power of predictive analytics with Quebit. 
"""
video = true

[[params.two.section]]
img = "images/optimise.jpg"
title = 'Optimise'
body = """
Quebit is revolutionising traffic management with cutting-edge vehicle counting technology. Say goodbye to manual data collection and guesswork. Using this real-time data, Quebit finds the optimal approach to manage varying traffic patterns, efficiently clearing queues and reducing traffic congestion. Don't settle for outdated systems, and let Quebit take your traffic management to the next level. 
"""


 [params.three]
 enable = true
 title = 'Vehicle Recognition'
 body = '''
 Use our state-of-the-art vehicle recognition technology to monitor traffic.
 '''
 
 [[params.three.feature]]
 icon = "fa-car"
 title = "Vehicle counts"
 body = "Revolutionize the way you monitor traffic with our cutting-edge vehicle counting program! Say goodbye to manual counting methods and hello to precise, real-time data thanks to our advanced image processing technology."
 
 [[params.three.feature]]
 icon = "fa-bus"
 title = "Classification"
 body = "Experience the future of vehicle surveillance with our state-of-the-art vehicle classification program. Get fine-grained information about their color, make and category (17 different categories), all made possible through cutting-edge technology and algorithms."
 
 [[params.three.feature]]
 icon = "fa-motorcycle"
 title = "OCR"
 body = "Streamline your traffic management with our innovative number plate recognition program. Enjoy automatic updates that accurately track and store vehicle information. With the added ability to generate automated fines, you can ensure that traffic regulations are upheld with ease."
 
 [[params.three.feature]]
 icon = "fa-bolt"
 title = "Fast API"
 body = "Unleash the power of lightning-fast traffic management with our API-based solution. Our API seamlessly integrates all of our vehicle counting, classification, and number plate recognition technologies, providing you with immediate and accurate data in real-time, allowing you to make informed decisions quickly and efficiently."


# [[params.three.feature]]
# icon = "fa-heart-o"
# title = "Some latin text"
# body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."
# 
# [[params.three.feature]]
# icon = "fa-flag-o"
# title = "Nothing important"
# body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

# [params.cta]
# enable = true
# title = "Arcue ut vel commodo"
# body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."
# 
# [[params.cta.link]]
# href = "#"
# text = "Activate"
# special = true
# 
# [[params.cta.link]]
# href = "#"
# text = "Learn More"
# special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "moqykozj"

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
